version: '3.1'

services:
  web:
    build: .
    ports:
      - "6500:5000"
    env_file:
      - .env  # Load the environment variables from the .env file
    secrets:
      - weather_api_key
    environment:
      WEATHER_API_KEY_FILE: /run/secrets/weather_api_key
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure

secrets:
  weather_api_key:
    file: ./secrets/weather_api_key
