version: '3.1'

services:
  web:
    build: .
    ports:
      - "6500:5000"
    environment:
      WEATHER_API_KEY: "${WEATHER_API_KEY}"  # Directly use the environment variable passed by Jenkins
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
      restart_policy:
        condition: on-failure
