- name: Update apt cache
  apt:
    update_cache: yes
    force_apt_get: yes

- name: Install Docker
  apt:
    name: docker.io
    state: present

- name: Install Docker Compose
  apt:
    name: docker-compose
    state: present

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
